routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('about', function () { return view('about'); })->name('about');
//Route::get('admin', function () { return view('admin.index'); })->name('admin');
Route::get('area', function () { return view('area'); })->name('area');
Route::get('admin', 'StatisticController@index')->name('admin');
Route::get('admin/films', 'StatisticController@films')->name('view_films');
Route::get('admin/films/sort', 'StatisticController@sortFilms')->name('sort_films');
Route::get('admin/tidings', 'StatisticController@tidings')->name('view_tidings');
Route::get('admin/tidings/sort', 'StatisticController@sortTidings')->name('sort_tidings');

Route::get('/', 'FilmController@viewNew')->name('home');
Route::get('films', 'FilmController@viewFilms')->name('films');
Route::get('serials', 'FilmController@viewSerials')->name('serials');
Route::get('search', 'FilmController@search')->name('search');
Route::get('show/{film}', 'FilmController@viewShow')->name('show');
Route::get('rating', 'FilmController@rating')->name('rating');
Route::group(['prefix'=>'admin'], function()
	{
		Route::get('create', 'FilmController@create')->name('film_create');
		Route::post('create', 'FilmController@store')->name('film_store');
		Route::get('edit/{film}', 'FilmController@edit')->name('film_edit');
		Route::post('edit/{film}', 'FilmController@update')->name('film_update');
		Route::get('{film}/delete', 'FilmController@delete')->name('film_delete');
		Route::resource('users', 'UserController');
	});

Route::resource('tidings', 'TidingController');
Route::resource('notes', 'NoteController');

//Комментарии для фильмов
Route::post('show/{film}/comments', 'CommentController@store')->middleware('auth')->name('comments');
Route::get('show/{film}/comments/edit/{comment}', 'CommentController@edit')->name('edit');
Route::post('show/{film}/comments/edit/{comment}', 'CommentController@update')->name('update');
Route::get('show/{film}/delete', 'CommentController@delete')->name('delete');

//Комментарии для новостей
Route::post('tidings/{tiding}/comments', 'CommentController@t_store')->middleware('auth')->name('t_comments');
Route::get('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_edit')->name('t_edit');
Route::post('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_update')->name('t_update');
Route::get('tidings/{tiding}/delete', 'CommentController@t_delete')->name('t_delete');

//Лайки для комментариев
Route::get('show/{film}/comments/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');

/*Route::get('show/{film}/comments/{comment}/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/{comment}/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');*/

Route::get('ajax', function () { return view('ajax'); })->name('ajax');
Route::post('ajax', 'CommentController@ajax')->middleware('auth')->name('cajax');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $table = 'film_user';

    protected $fillable = ['film_id', 'season', 'series'];
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Http\Request;
use App\User;
use App\Film;
use App\Note;

class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notes = Note::all();
        $user = User::find(auth()->user()->id);
        return view('notes.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::find(auth()->user()->id);
        $films = Film::all();
        return view('notes.create', compact('user', 'films'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Film $film)
    {   
        $user = auth()->user();
        $user->notes()->attach(
            $request->name,
            ['season' => $request->season,
            'series' => $request->series]
        );
        return redirect()->route('notes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($note)
    {
        $film = Film::find($note);
        $films = Film::all();
        $user = auth()->user();
        $note = Note::where('film_id', $note)->where('user_id', $user->id)->first();

        return view('notes.edit', compact('user', 'note', 'films', 'film'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Note $note, Film $film)
    {
        $note = Note::find($note->id)->update([
            'film_id' => $request->name,
            'season' => $request->season,
            'series' => $request->series
        ]);

        return redirect()->route('notes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = auth()->user();
        $user->notes()->detach($id);
        return redirect()->route('notes.index');
    }
}

resources/views/notes/create.blade.php
@extends('app')

@section('title')
	Фильмы
@endsection

@section('content')
	<h2>Личный кабинет</h2><hr>
	<div class="container">
  		<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Аниме</th>
		      <th scope="col" class="text-center">Сезон</th>
		      <th scope="col" class="text-center">Серия</th>
		      <th scope="col" class="text-center">Добавить</th>
		    </tr>
		  </thead>
		  <tbody>
  			<form action="{{route('notes.store')}}" method="POST">
				@csrf
			    <tr>
			      	<td class="text-center">
			      		<div class="mb-3">
						    <select class="custom-select" name="name" required>
						      	<option value="">Choose...</option>
						      	@foreach($films as $film)
						      		<option value="{{$film->id}}">{{$film->name}}</option>
					      		@endforeach
						    </select>
						</div>
			      	</td>
			      	<td class="text-center">
			      		<input type="text" name="season">
			      	</td>
			      	<td class="text-center">
			      		<input type="text" name="series">
			      	</td>
			      	<td class="text-center">
			      		<button class="btn btn-dark" type="submit">
			      			<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						  		<path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
						  		<path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
							</svg>
			      		</button>
		      		</td>
			    </tr>
    		</form>
			    @foreach($user->notes as $note)
				    <tr>
				      	<td class="text-center"><a href="{{route('show', $note->id)}}">{{$note->name}}</a></td>
				      	<td class="text-center">{{$note->pivot->season}}</td>
				      	<td class="text-center">{{$note->pivot->series}}</td>
				      	<td class="text-center">
				      		<a href="{{route('notes.edit', $note->id)}}" class="btn btn-dark">
			    				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					  				<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
								</svg>
						</a>
			      		<form action="{{route('notes.destroy', $note->id)}}" method="POST" class="d-inline">
			    			{{ method_field('DELETE') }}
			    			@csrf
			    			<button type="submit" class="btn btn-danger">&cross;</button>
			    		</form>
				      	</td>
			    	</tr>
		   		 @endforeach
		  </tbody>
		</table>			
	</div>	
@endsection

resources/views/notes/edit.blade.php
@extends('app')

@section('title')
	Фильмы
@endsection

@section('content')
	<h2>Личный кабинет</h2><hr>
	<div class="container">
  		<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Аниме</th>
		      <th scope="col" class="text-center">Сезон</th>
		      <th scope="col" class="text-center">Серия</th>
		      <th scope="col" class="text-center">Редактировать</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<form action="{{route('notes.update', [$note, $film])}}" method="POST">
	  			{{ method_field('PUT') }}
				@csrf 
			    <tr>
			      	<td class="text-center">
			      		<div class="mb-3">
						    <select class="custom-select" name="name" required>
						      	<option value="{{$film->id}}">{{$film->name}}</option>
						      	@foreach($films as $film)
						      		<option value="{{$film->id}}">{{$film->name}}</option>
					      		@endforeach
						    </select>
						</div>
			      	</td>
			      	<td class="text-center">
			      		<input type="text" name="season" value="{{$note->season}}">
			      	</td>
			      	<td class="text-center">
			      		<input type="text" name="series" value="{{$note->series}}">
			      	</td>
			      	<td class="text-center">
			      		<button type="submit" class="btn btn-dark">
		    				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							  	<path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
							  	<path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
							</svg>
						</button>
			      	</td>
			    </tr>
		    </form>
			    @foreach($user->notes as $note)
				    <tr>
				      	<td class="text-center"><a href="{{route('show', $note->id)}}">{{$note->name}}</a></td>
				      	<td class="text-center">{{$note->pivot->season}}</td>
				      	<td class="text-center">{{$note->pivot->series}}</td>
				      	<td class="text-center">
			      		<a href="{{route('notes.update', $note->id)}}" class="btn btn-dark">
			    				<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					  				<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
								</svg>
						</a>
			      		<form action="{{route('notes.destroy', $note->id)}}" method="POST" class="d-inline">
			    			{{ method_field('DELETE') }}
			    			@csrf
			    			<button type="submit" class="btn btn-danger">&cross;</button>
			    		</form>
				      	</td>
			    	</tr>
		   		 @endforeach
		  </tbody>
		</table>
	</div>	
@endsection

resources/views/notes/index.blade.php
@extends('app')

@section('title')
	Фильмы
@endsection

@section('content')
	<h2>Личный кабинет</h2><hr>
	<div class="container">
  		<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Аниме</th>
		      <th scope="col" class="text-center">Сезон</th>
		      <th scope="col" class="text-center">Серия</th>
		      <th scope="col" class="text-center">Действие</th>
		    </tr>
		  </thead>
		  <tbody>
		  		@foreach($user->notes as $note)
				    <tr>
				      	<td class="text-center"><a href="{{route('show', $note)}}">{{$note->name}}</a></td>
				      	<td class="text-center">{{$note->pivot->season}}</td>
				      	<td class="text-center">{{$note->pivot->series}}</td>
				      	<td class="text-center"> 
			      			<a href="{{route('notes.edit', $note)}}" class="btn btn-dark">
				    			<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						  			<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
								</svg>
							</a>
				      		<form action="{{route('notes.destroy', $note->id)}}" method="POST" class="d-inline">
				    			{{ method_field('DELETE') }}
				    			@csrf
				    			<button type="submit" class="btn btn-danger">&cross;</button>
				    		</form>

				      	</td>
				    </tr>
			    @endforeach
		  </tbody>
		</table>
		<p><a href="{{route('notes.create')}}" class="btn btn-dark float-right" type="submit">Добавить запись</a></p>
	</div>	
@endsection