routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('about', function () { return view('about'); })->name('about');
//Route::get('admin', function () { return view('admin.index'); })->name('admin');
Route::get('area', function () { return view('area'); })->name('area');
Route::get('admin', 'StatisticController@index')->name('admin');
Route::get('admin/films', 'StatisticController@films')->name('view_films');
Route::get('admin/films/sort', 'StatisticController@sortFilms')->name('sort_films');
Route::get('admin/tidings', 'StatisticController@tidings')->name('view_tidings');
Route::get('admin/tidings/sort', 'StatisticController@sortTidings')->name('sort_tidings');

Route::get('/', 'FilmController@viewNew')->name('home');
Route::get('films', 'FilmController@viewFilms')->name('films');
Route::get('serials', 'FilmController@viewSerials')->name('serials');
Route::get('search', 'FilmController@search')->name('search');
Route::get('show/{film}', 'FilmController@viewShow')->name('show');
Route::get('rating', 'FilmController@rating')->name('rating');
Route::group(['prefix'=>'admin'], function()
	{
		Route::get('create', 'FilmController@create')->name('film_create');
		Route::post('create', 'FilmController@store')->name('film_store');
		Route::get('edit/{film}', 'FilmController@edit')->name('film_edit');
		Route::post('edit/{film}', 'FilmController@update')->name('film_update');
		Route::get('{film}/delete', 'FilmController@delete')->name('film_delete');
		Route::resource('users', 'UserController');
	});

Route::resource('tidings', 'TidingController');
Route::resource('notes', 'NoteController');

//Комментарии для фильмов
Route::post('show/{film}/comments', 'CommentController@store')->middleware('auth')->name('comments');
Route::get('show/{film}/comments/edit/{comment}', 'CommentController@edit')->name('edit');
Route::post('show/{film}/comments/edit/{comment}', 'CommentController@update')->name('update');
Route::get('show/{film}/delete', 'CommentController@delete')->name('delete');

//Комментарии для новостей
Route::post('tidings/{tiding}/comments', 'CommentController@t_store')->middleware('auth')->name('t_comments');
Route::get('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_edit')->name('t_edit');
Route::post('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_update')->name('t_update');
Route::get('tidings/{tiding}/delete', 'CommentController@t_delete')->name('t_delete');

//Лайки для комментариев
Route::get('show/{film}/comments/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');

/*Route::get('show/{film}/comments/{comment}/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/{comment}/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');*/

Route::get('ajax', function () { return view('ajax'); })->name('ajax');
Route::post('ajax', 'CommentController@ajax')->middleware('auth')->name('cajax');

resources/views/inc/comments.blade.php
<div class="container">
	<div class="row">
		@foreach($film->comments as $comment)
			<div class="card col-12">
			  <div class="card-header">
			    User_name
			  </div>
			  <div class="card-body">
			    <blockquote class="blockquote mb-0">
			      <p>{{$comment->text}}</p>
			      <footer class="blockquote-footer">{{$comment->created_at}}</footer>
			    </blockquote>
			  </div>
			</div>
		@endforeach
	</div>
</div>

resources/views/inc/errors.blade.php
@if(count($errors))
	<div class="alert alert-danger">
		<strong>Упс! Что-то пошло не так..</strong>
		<ul>
			@foreach($errors->all() as $error)
				<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
@endif

@if(session('success'))
	<div class="alert alert-success">
		{{session('success')}}
	</div>
@endif

resources/views/inc/footer.blade.php
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
  	<hr>
    <p><span style="color: black">Blog template built for</span> <a href="https://getbootstrap.com/">Bootstrap</a> <span style="color: black">by</span> <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p> <a href="#">Back to top</a> </p>
  </div>
</footer>

resources/views/inc/header.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbg">
  <img src="/img/2к.jpg" width="35" height="38" id="header">
  <a href="/" class="link"><h1>AniMonster</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Новинки <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('films')}}">Фильмы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('serials')}}" tabindex="-1" aria-disabled="true">Сериалы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('rating')}}" tabindex="-1" aria-disabled="true">Рейтинг</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('tidings.index')}}" tabindex="-1" aria-disabled="true">Новости</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('about')}}" tabindex="-1" aria-disabled="true">О нас</a>
      </li>
    </ul>
  </div>


  @if (Route::has('login'))
    @auth
      <div>
        <a href="
          @if(Auth::user()->role == 'admin')
            {{route('admin')}}
          @else
            {{ route('notes.index') }}
          @endif
        ">{{Auth::user()->name}} </a> |
        <a href="{{ route('logout') }}" onclick="event.preventDefault();
          document.getElementById('logout-form').submit();"> {{ __('Выход') }}</a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
      </div>
  @else
      <div>
        <a href="{{ route('login') }}">Войти </a> |
        <a href="{{ route('register') }}"> Регистрация</a>
      </div>
    @endauth
  @endif



</nav>
<div class="container">
  <form action="" role="search" class="search d-lg-none d-xl-none">
    <div class="input-group mb-3">
      <input type="search" class="form-control" placeholder="найти.." aria-label="Recipient's username" aria-describedby="button-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" id="button-addon2">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
            <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
          </svg>
        </button>
      </div>
    </div>
  </form>
</div>

resources/views/inc/panel.blade.php
<div class="card card-info d-none d-lg-block d-xl-block " id="search">
	<div class="card-header">
		<div class="sidebar-header">Поиск</div>
	</div>
	<div class="card-body">
		<form action="{{route('search')}}" role="search" method="get">
		    <div class="input-group mb-3">
		      <input type="search" class="form-control" name="search" placeholder="найти.." aria-label="Recipient's username" aria-describedby="button-addon2">
		      <div class="input-group-append">
		        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
		          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
		            <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
		            <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
		          </svg>
		        </button>
		      </div>
		    </div>
		</form>
    </div>
</div>
<br>
<div class="card card-info">
	<div class="card-header">
		<div class="sidebar-header"><a href="{{route('tidings.index')}}" class="rating">Последние новости</a></div>
	</div>
	<div class="card-body">
		@foreach($last_tidings as $tiding)
			<p><a href="{{route('tidings.show', $tiding->id)}}">{{$tiding->title}}</a></p>
		@endforeach
	</div>
</div>
<br>
<div class="card card-info">
	<div class="card-header">
		<div class="sidebar-header"><a href="{{route('rating')}}" class="rating">Топ 5 аниме</a></div>
	</div>
	<div class="card-body">
		<ul class="list-group">
			@foreach($films_rating as $film)
		        <li class="list-group-item list-group-warning">
		          <a href="{{route('show', $film->id)}}">{{$film->name}}</a>
		          <span class="badge float-right">{{$film->rating}}</span>
		        </li>
	        @endforeach
    	</ul>
	</div>
</div>

resources/views/inc/try.blade.php
@if (Route::has('login'))
      <div class="top-right links">
          @auth
              <a href="{{ url('/area') }}">
                <ul class="navbar-nav ml-auto">
                  <!-- Authentication Links -->
                  @guest
                      <li class="nav-item">
                          <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                      </li>
                      @if (Route::has('register'))
                          <li class="nav-item">
                              <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                          </li>
                      @endif
                  @else
                      <li class="nav-item dropdown">
                          <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                              {{ Auth::user()->name }} <span class="caret"></span>
                          </a>

                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{{ route('area') }}">
                                 Личный кабинет
                              </a>
                              <a class="dropdown-item" href="{{ route('logout') }}"
                                 onclick="event.preventDefault();
                                               document.getElementById('logout-form').submit();">
                                  {{ __('Выход') }}
                              </a>

                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                  @csrf
                              </form>
                          </div>
                      </li>
                  @endguest
                </ul>
              </a>
            @else
              <a href="{{ route('login') }}">Войти</a> | 

            @if (Route::has('register'))
                <a href="{{ route('register') }}">Регистрация</a>
            @endif
          @endauth
      </div>
    @endif