routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('about', function () { return view('about'); })->name('about');
//Route::get('admin', function () { return view('admin.index'); })->name('admin');
Route::get('area', function () { return view('area'); })->name('area');
Route::get('admin', 'StatisticController@index')->name('admin');
Route::get('admin/films', 'StatisticController@films')->name('view_films');
Route::get('admin/films/sort', 'StatisticController@sortFilms')->name('sort_films');
Route::get('admin/tidings', 'StatisticController@tidings')->name('view_tidings');
Route::get('admin/tidings/sort', 'StatisticController@sortTidings')->name('sort_tidings');

Route::get('/', 'FilmController@viewNew')->name('home');
Route::get('films', 'FilmController@viewFilms')->name('films');
Route::get('serials', 'FilmController@viewSerials')->name('serials');
Route::get('search', 'FilmController@search')->name('search');
Route::get('show/{film}', 'FilmController@viewShow')->name('show');
Route::get('rating', 'FilmController@rating')->name('rating');
Route::group(['prefix'=>'admin'], function()
	{
		Route::get('create', 'FilmController@create')->name('film_create');
		Route::post('create', 'FilmController@store')->name('film_store');
		Route::get('edit/{film}', 'FilmController@edit')->name('film_edit');
		Route::post('edit/{film}', 'FilmController@update')->name('film_update');
		Route::get('{film}/delete', 'FilmController@delete')->name('film_delete');
		Route::resource('users', 'UserController');
	});

Route::resource('tidings', 'TidingController');
Route::resource('notes', 'NoteController');

//Комментарии для фильмов
Route::post('show/{film}/comments', 'CommentController@store')->middleware('auth')->name('comments');
Route::get('show/{film}/comments/edit/{comment}', 'CommentController@edit')->name('edit');
Route::post('show/{film}/comments/edit/{comment}', 'CommentController@update')->name('update');
Route::get('show/{film}/delete', 'CommentController@delete')->name('delete');

//Комментарии для новостей
Route::post('tidings/{tiding}/comments', 'CommentController@t_store')->middleware('auth')->name('t_comments');
Route::get('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_edit')->name('t_edit');
Route::post('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_update')->name('t_update');
Route::get('tidings/{tiding}/delete', 'CommentController@t_delete')->name('t_delete');

//Лайки для комментариев
Route::get('show/{film}/comments/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');

/*Route::get('show/{film}/comments/{comment}/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/{comment}/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');*/

Route::get('ajax', function () { return view('ajax'); })->name('ajax');
Route::post('ajax', 'CommentController@ajax')->middleware('auth')->name('cajax');

app/Tiding.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Comment;
use App\User;

class Tiding extends Model
{
    protected $fillable = ['title', 'body', 'img'];

    public function comments()
    {
    	return $this->morphMany(Comment::class, 'commentable');
    }

    public function addComment($text)
    {
    	Comment::create([
    		'text' => $text,
    		'commentable_id' => $this->id,
            'commentable_type' => get_class($this),
    		'user_id' => auth()->id()
    	]);
    }
}

app/Http/Controllers/TidingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Comment;
use App\User;
use App\Tiding;

class TidingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tidings = Tiding::latest()->paginate(3);
        return view('tiding.index', compact('tidings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tiding.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tiding = Tiding::create([
            'title' => $request->title,
            'body' => $request->body,
            'img' => $request->img
        ]);

        return redirect()->route('tidings.show', compact('tiding'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Tiding $tiding)
    {
        event('tidingHasViewed', $tiding);
        return view('tiding.show', compact('tiding'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tiding $tiding)
    {
        return view('tiding.edit', compact('tiding'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Tiding $tiding, Request $request)
    {
        $up_tiding = Tiding::find($tiding->id)->update([
            'title' => $request->title,
            'body' => $request->body,
            'img' => $request->img
        ]);

        return redirect()->route('tidings.show', compact('tiding'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tiding = Tiding::find($id)->delete();
        return redirect()->route('tidings.index');
    }
}

resources/views/tiding/create.blade.php
@extends('admin.app')

@section('title')
	Добавить новость
@endsection

@section('content')
	<h2>Добавить фильм</h2>
	<div class="card">
		<div class="card-body">
			<form action="{{route('tidings.store')}}" method="POST">
				@csrf
				<div class="form-group">
				    <label for="img">Постер</label>
				    <input type="text" name="img" class="form-control" id="img" placeholder="URL постера">
			  	</div>
				<div class="form-group">
				    <label for="title">Заголовок</label>
				    <input type="text" name="title" class="form-control" id="title">
				</div>
				<div class="form-group">
				    <label for="body">Текст новости</label>
				    <textarea type="text" name="body" class="form-control" id="body"></textarea>
				</div>
			  	<button type="submit" class="btn btn-dark float-right">Добавить</button>
			</form>
		</div>
	</div>
@endsection

resources/views/tiding/edit.blade.php
@extends('admin.app')

@section('title')
	Редактирование новости
@endsection

@section('content')
	<h2>Редактировать новость</h2>
	<div class="card">
		<div class="card-body">
			<form action="{{route('tidings.update', $tiding->id)}}" method="POST">
				{{ method_field('PUT') }}
				@csrf 
				<div class="form-group">
				    <label for="img">Постер</label>
				    <input type="text" name="img" class="form-control" id="img" placeholder="URL постера" value="{{$tiding->img}}">
			  	</div>
				<div class="form-group">
				    <label for="title">Заголовок</label>
				    <input type="text" name="title" class="form-control" id="title" value="{{$tiding->title}}">
				</div>
				<div class="form-group">
				    <label for="body">Текст новости</label>
				    <textarea type="text" name="body" class="form-control" id="body">{{$tiding->body}}</textarea>
				</div>
			  	<button type="submit" class="btn btn-dark float-right">Редактировать</button>
			</form>
		</div>
	</div>
@endsection

resources/views/tiding/edit_comment.blade.php
@extends('app')

@section('title')
	AniMonster
@endsection

@section('content')
	<div class="card mb-3">
	  <img src="{{$tiding->img}}" class="card-img-top" alt="...">
	  <div class="card-body">
	    <h5 class="card-title">{{$tiding->title}}</h5>
	    <p class="card-text">{{$tiding->body}}</p>
	    <p class="card-text"><small class="text-muted">{{$tiding->created_at}}</small></p>
	  </div>
	</div>
	<br><hr><br>

	@include('inc.errors')
	<div class="container">
		<form method="POST" action="{{route('t_update', [$tiding->id, $comment->id])}}" class="card col-12">
			@csrf
			<div class="card-block form-group mt-3">
				<input type="text" name="text" value="{{$comment->text}}" class="form-control">
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-dark float-right">Редактировать комментарий</button>
			</div>
		</form>
	</div>
	<br><hr><br>
	<div class="container">
		@foreach($tiding->comments as $comment)
			<div class="card mb-3">
			  <div class="card-header">
		  		@if(isset($comment->user->name))
			    	{{$comment->user->name}}
				    @if($comment->user->id == auth()->id())
					    <a href="{{route('delete', $comment->id)}}" class="btn btn-danger float-right">&cross;</a>
					    <a href="{{route('edit', [$tiding->id, $comment->id])}}" class="btn btn-light float-right">
				    		<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						  		<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
							</svg>
						</a>
				    @endif
			    @else
		    		Пользователь удален
	    		@endif
			  </div>
			  <div class="card-body">
			    <blockquote class="blockquote mb-0">
			      <p>{{$comment->text}}</p>
			      <footer class="blockquote-footer">{{$comment->created_at->diffForHumans()}}
			      		<a href="
			      			@if($comment->liked()->find(auth()->id()))
			      				{{route('dislike', [$tiding->id, $comment->id])}}
		      				@else
		      					{{route('like', [$tiding->id, $comment->id])}}
	      					@endif
			      			" class="float-right">{{$comment->like_comment}} &hearts;
			      		</a>
			      </footer>
			    </blockquote>
			  </div>
			</div>
		@endforeach
	</div>
@endsection

resources/views/tiding/index.blade.php
@extends('app')

@section('title')
	AniMonster
@endsection

@section('content')
	<h2>Новости</h2><hr>
	@foreach($tidings as $tiding)
		<div class="card mb-3">
		  <img src="{{$tiding->img}}" class="card-img-top" alt="...">
		  <div class="card-body">
		    <h5 class="card-title" style="color: #fffff3">{{$tiding->title}}</h5>
		    <p class="card-text"><small class="text-muted align-bottom">{{$tiding->created_at}}</small>
	    	<a href="{{route('tidings.show', $tiding->id)}}" class="btn btn-dark float-right">Подробнее</a></p>
		  </div>
		</div>
	@endforeach
	<div class="float-right">{{$tidings->render()}}</div>
@endsection

resources/views/tiding/show.blade.php
@extends('app')

@section('title')
	AniMonster
@endsection

@section('content')
	<div class="card mb-3">
	  <img src="{{$tiding->img}}" class="card-img-top" alt="...">
	  <div class="card-body">
	    <h5 class="card-title" style="color: red">{{$tiding->title}}
	    	@if(auth()->user()!==null)
		    	@if(auth()->user()->role == 'admin')
		    		<form action="{{route('tidings.destroy', $tiding->id)}}" method="POST">
		    			{{ method_field('DELETE') }}
		    			@csrf
		    			<button type="submit" class="btn btn-danger float-right">&cross;</button>
		    		</form>
				    <a href="{{route('tidings.edit', $tiding->id)}}" class="btn btn-dark float-right">
			    		<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					  		<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
						</svg>
					</a>
		    	@endif
	    	@endif
	    </h5>
	    <p class="card-text">{{$tiding->body}}</p>
	    <p class="card-text"><small class="text-muted">{{$tiding->created_at}}</small>
	    	<span class="badge badge-dark badge-pill float-right">{{$tiding->view_count}}</span>
	    	<span class="float-right">Просмотров</span>
	    </p>
	  </div>
	</div>
	<br><hr><h2>Комментарии</h2><br>
	<div class="container">
		@foreach($tiding->comments as $comment)
			<div class="card mb-3">
			  <div class="card-header">
		  		@if(isset($comment->user->name))
			    	{{$comment->user->name}}
				    @if($comment->user->id == auth()->id())
					    <a href="{{route('t_delete', $comment->id)}}" class="btn btn-danger float-right">&cross;</a>
					    <a href="{{route('t_edit', [$tiding->id, $comment->id])}}" class="btn btn-light float-right">
				    		<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						  		<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
							</svg>
						</a>
				    @endif
			    @else
		    		- Пользователь удален -
	    		@endif
			  </div>
			  <div class="card-body">
			    <blockquote class="blockquote mb-0">
			      <p>{{$comment->text}}</p>
			      <footer class="blockquote-footer">{{$comment->created_at->diffForHumans()}}
			      		<a href="
			      			@if($comment->liked()->find(auth()->id()))
			      				{{route('dislike', [$tiding->id, $comment->id])}}
		      				@else
		      					{{route('like', [$tiding->id, $comment->id])}}
	      					@endif
			      			" class="float-right">{{$comment->like_comment}} &hearts;
			      		</a>
			      </footer>
			    </blockquote>
			  </div>
			</div>
		@endforeach
	</div>

	<br><hr><br>

	<div class="container">
		<form method="POST" action="{{route('t_comments', $tiding->id)}}" class="card col-12">
			@csrf
			<div class="card-block form-group mt-3">
				<input type="text" name="text" placeholder="Ваш комментарий.." class="form-control">
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-dark float-right">Добавить комментарий</button>
			</div>
		</form>
	</div>
@endsection