routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('about', function () { return view('about'); })->name('about');
//Route::get('admin', function () { return view('admin.index'); })->name('admin');
Route::get('area', function () { return view('area'); })->name('area');
Route::get('admin', 'StatisticController@index')->name('admin');
Route::get('admin/films', 'StatisticController@films')->name('view_films');
Route::get('admin/films/sort', 'StatisticController@sortFilms')->name('sort_films');
Route::get('admin/tidings', 'StatisticController@tidings')->name('view_tidings');
Route::get('admin/tidings/sort', 'StatisticController@sortTidings')->name('sort_tidings');

Route::get('/', 'FilmController@viewNew')->name('home');
Route::get('films', 'FilmController@viewFilms')->name('films');
Route::get('serials', 'FilmController@viewSerials')->name('serials');
Route::get('search', 'FilmController@search')->name('search');
Route::get('show/{film}', 'FilmController@viewShow')->name('show');
Route::get('rating', 'FilmController@rating')->name('rating');
Route::group(['prefix'=>'admin'], function()
	{
		Route::get('create', 'FilmController@create')->name('film_create');
		Route::post('create', 'FilmController@store')->name('film_store');
		Route::get('edit/{film}', 'FilmController@edit')->name('film_edit');
		Route::post('edit/{film}', 'FilmController@update')->name('film_update');
		Route::get('{film}/delete', 'FilmController@delete')->name('film_delete');
		Route::resource('users', 'UserController');
	});

Route::resource('tidings', 'TidingController');
Route::resource('notes', 'NoteController');

//Комментарии для фильмов
Route::post('show/{film}/comments', 'CommentController@store')->middleware('auth')->name('comments');
Route::get('show/{film}/comments/edit/{comment}', 'CommentController@edit')->name('edit');
Route::post('show/{film}/comments/edit/{comment}', 'CommentController@update')->name('update');
Route::get('show/{film}/delete', 'CommentController@delete')->name('delete');

//Комментарии для новостей
Route::post('tidings/{tiding}/comments', 'CommentController@t_store')->middleware('auth')->name('t_comments');
Route::get('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_edit')->name('t_edit');
Route::post('tidings/{tiding}/comments/edit/{comment}', 'CommentController@t_update')->name('t_update');
Route::get('tidings/{tiding}/delete', 'CommentController@t_delete')->name('t_delete');

//Лайки для комментариев
Route::get('show/{film}/comments/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');

/*Route::get('show/{film}/comments/{comment}/like', 'CommentController@like')->middleware('auth')->name('like');
Route::get('show/{film}/comments/{comment}/dislike', 'CommentController@dislike')->middleware('auth')->name('dislike');*/

Route::get('ajax', function () { return view('ajax'); })->name('ajax');
Route::post('ajax', 'CommentController@ajax')->middleware('auth')->name('cajax');

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" href="/css/style.css">
	<title>@yield('title')</title>
</head>
<body>
	@include('inc.header')
	<br><br>
	<div class="container">
		<div class="row">
			<div class="col-lg-9 order-lg-2 col-sm-12">
				@yield('content')
			</div>
			<div class="col-lg-3 order-lg-1 col-sm-12">
				@include('admin.inc.panel')
			</div>
		</div>
	</div>
	@include('inc.footer')
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

resources/views/admin/create.blade.php
@extends('admin.app')

@section('title')
	Добавить фильм
@endsection

@section('content')
	<h2>Добавить фильм</h2><hr>
	<div class="card">
		<div class="card-body">
			<form action="{{route('film_store')}}" method="POST">
				@csrf
			  <div class="form-group">
			    <label for="name">Название</label>
			    <input type="text" name="name" class="form-control" id="name">
			  </div>
			  <div class="form-group">
			    <label for="description">Описание</label>
			    <textarea type="text" name="description" class="form-control" id="description"></textarea>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="poster">Постер</label>
			      <input type="text" name="poster" class="form-control" id="poster"  placeholder="URL картинки">
			    </div>
			    <div class="form-group col-md-6">
			      <label for="frame">Фрейм</label>
			      <input type="text" name="frame" class="form-control" id="frame"  placeholder="youtube->поделиться->встроить">
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="author">Автор</label>
			      <input type="text" name="author" class="form-control" id="author">
			    </div>
			    <div class="form-group col-md-4">
			      <label for="year">Год</label>
			      <input type="text" name="year" class="form-control" id="year">
			    </div>
			    <div class="form-group col-md-2">
			      <label for="rating">Рейтинг</label>
			      <input type="text" name="rating" class="form-control" id="rating">
			    </div>
			  </div>
			  <fieldset class="form-group">
			    <div class="row">
			      <legend class="col-form-label col-sm-2 pt-0"><p>Категория</p></legend>
			      <div class="col-sm-10">
			        <div class="custom-control custom-radio custom-control-inline">
					  <input type="radio" id="film" name="category" value="1" class="custom-control-input">
					  <label class="custom-control-label" for="film">Фильм</label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
					  <input type="radio" id="serial" name="category" value="2" class="custom-control-input">
					  <label class="custom-control-label" for="serial">Сериал</label>
					</div>
			      </div>
			    </div>
			  </fieldset>
			  <button type="submit" class="btn btn-primary float-right">Добавить</button>
			</form>
		</div>
	</div>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.app')

@section('title')
	Редактирование фильма
@endsection

@section('content')
	<h2>Редактировать фильм</h2><hr>
	<div class="card">
		<div class="card-body">
			<form action="{{route('film_update', $film->id)}}" method="POST">
				@csrf
			  <div class="form-group">
			    <label for="name">Название</label>
			    <input type="text" name="name" class="form-control" id="name" value="{{$film->name}}">
			  </div>
			  <div class="form-group">
			    <label for="description">Описание</label>
			    <textarea type="text" name="description" class="form-control" id="description">{{$film->description}}</textarea>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="poster">Постер</label>
			      <input type="text" name="poster" class="form-control" id="poster"  placeholder="URL картинки" value="{{$film->poster}}">
			    </div>
			    <div class="form-group col-md-6">
			      <label for="frame">Фрейм</label>
			      <input type="text" name="frame" class="form-control" id="frame"  placeholder="youtube->поделиться->встроить" value="{{$film->frame}}">
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="author">Автор</label>
			      <input type="text" name="author" class="form-control" id="author" value="{{$film->author}}">
			    </div>
			    <div class="form-group col-md-4">
			      <label for="year">Год</label>
			      <input type="text" name="year" class="form-control" id="year" value="{{$film->year}}">
			    </div>
			    <div class="form-group col-md-2">
			      <label for="rating">Рейтинг</label>
			      <input type="text" name="rating" class="form-control" id="rating" value="{{$film->rating}}">
			    </div>
			  </div>
			  <fieldset class="form-group">
			    <div class="row">
			      <legend class="col-form-label col-sm-2 pt-0"><p>Категория</p></legend>
			      <div class="col-sm-10">
			        <div class="custom-control custom-radio custom-control-inline">
					  <input type="radio" id="film" name="category" value="1" class="custom-control-input"
					  @if($film->category = 1) checked @endif>
					  <label class="custom-control-label" for="film">Фильм</label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
					  <input type="radio" id="serial" name="category" value="2" class="custom-control-input" @if($film->category = 2) checked @endif>
					  <label class="custom-control-label" for="serial">Сериал</label>
					</div>
			      </div>
			    </div>
			  </fieldset>
			  <button type="submit" class="btn btn-primary float-right">Редактировать</button>
			</form>
		</div>
	</div>
@endsection

resources/views/admin/films.blade.php
@extends('admin.app')

@section('title')
	Adminka
@endsection

@section('content')
	<div class="container">
		<h2>Статистика просмотра фильмов</h2><hr>
  		<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Аниме</th>
		      <th scope="col" class="text-center"><a href="{{route('view_films')}}">Просмотров</a></th>
		      <th scope="col" class="text-center"><a href="{{route('sort_films')}}">Комментариев</a></th>
		    </tr>
		  </thead>
		  <tbody>
		  	@foreach($films as $film)
			    <tr>
			      <td class="text-center"><a href="{{route('show', $film->id)}}">{{$film->name}}</a></td>
			      <td class="text-center">{{$film->view_count}}</td>
			      <td class="text-center">{{$film->comments->count()}}</td>
			    </tr>
			@endforeach
		  </tbody>
		</table> 
		<div class="float-right">{{$films->render()}}</div>	
	</div>
@endsection

resources/views/admin/index.blade.php
@extends('admin.app')

@section('title')
	Adminka
@endsection

@section('content')
	<div class="container">
		<h2>Кабинет администратора</h2><hr>
  		<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Дата</th>
		      <th scope="col" class="text-center">Посетителей</th>
		    </tr>
		  </thead>
		  <tbody>
		  	@foreach($statistics as $statistic)
			    <tr>
			      <td class="text-center">{{date("d.m.Y", strtotime($statistic->created_at))}}</td>
			      <td class="text-center">{{$statistic->visit}}</td>
			    </tr>
			@endforeach
		  </tbody>
		</table>
	</div>	  	
@endsection

resources/views/admin/sortfilms.blade.php
@extends('admin.app')

@section('title')
	Adminka
@endsection

@section('content')
	<div class="container">
		<h2>Статистика просмотра фильмов</h2><hr>
  		<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Аниме</th>
		      <th scope="col" class="text-center"><a href="{{route('view_films')}}">Просмотров</a></th>
		      <th scope="col" class="text-center"><a href="{{route('sort_films')}}">Комментариев</a></th>
		    </tr>
		  </thead>
		  <tbody>
		  	@foreach($films as $film)
			    <tr>
			      <td class="text-center"><a href="{{route('show', $film->id)}}">{{$film->name}}</a></td>
			      <td class="text-center">{{$film->view_count}}</td>
			      <td class="text-center">{{$film->comments->count()}}</td>
			    </tr>
			@endforeach
		  </tbody>
		</table> 
		<div class="float-right">{{$films->render()}}</div>	
	</div>
@endsection

resources/views/admin/sorttidings.blade.php
@extends('admin.app')

@section('title')
	Adminka
@endsection

@section('content')
	<div class="container">
		<h2>Статистика просмотра новостей </h2><hr>
	  	<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Новость</th>
		      <th scope="col" class="text-center"><a href="{{route('view_tidings')}}">Просмотров</a></th>
		      <th scope="col" class="text-center"><a href="{{route('sort_tidings')}}">Комментариев</a></th>
		    </tr>
		  </thead>
		  <tbody>
		  	@foreach($tidings as $tiding)
			    <tr>
			      <td class="text-center"><a href="{{route('tidings.show', $tiding->id)}}">{{$tiding->title}}</a></td>
			      <td class="text-center">{{$tiding->view_count}}</td>
			      <td class="text-center">{{$tiding->comments->count()}}</td>
			    </tr>
			@endforeach
		  </tbody>
		</table>	
		<div class="float-right">{{$tidings->render()}}</div>  	
	</div>
@endsection

resources/views/admin/tidings.blade.php
@extends('admin.app')

@section('title')
	Adminka
@endsection

@section('content')
	<div class="container">
		<h2>Статистика просмотра новостей </h2><hr>
	  	<table class="table table-striped table-dark">
		  <thead>
		    <tr>
		      <th scope="col" class="text-center">Новость</th>
		      <th scope="col" class="text-center"><a href="{{route('view_tidings')}}">Просмотров</a></th>
		      <th scope="col" class="text-center"><a href="{{route('sort_tidings')}}">Комментариев</a></th>
		    </tr>
		  </thead>
		  <tbody>
		  	@foreach($tidings as $tiding)
			    <tr>
			      <td class="text-center"><a href="{{route('tidings.show', $tiding->id)}}">{{$tiding->title}}</a></td>
			      <td class="text-center">{{$tiding->view_count}}</td>
			      <td class="text-center">{{$tiding->comments->count()}}</td>
			    </tr>
			@endforeach
		  </tbody>
		</table>	
		<div class="float-right">{{$tidings->render()}}</div>  	
	</div>
@endsection

resources/views/admin/users.blade.php
@extends('admin.app')

@section('title')
	Пользователи
@endsection

@section('content')
	<h2>Пользователи</h2><hr>
	<table class="table table-striped table-dark">
	  <thead>
	    <tr>
	      <th scope="col" class="text-center"><a href="{{route('users.create')}}">Пользователь</a></th>
	      <th scope="col" class="text-center">Email</th>
	      <th scope="col" class="text-center">Роль</th>
	      <th scope="col" class="text-center">Последняя активность</th>
	      <th scope="col" class="text-center">Редактировать</th>
	      <th scope="col" class="text-center">Удалить</th>
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($users as $user)
		    <tr>
		      	<td class="text-center">{{$user->name}}</td>
		      	<td class="text-center">{{$user->email}}</td>
		      	<td class="text-center">{{$user->role}}</td>
		      	<td class="text-center">??</td>
		      	<td class="text-center">
		      		<a href="{{route('users.edit', $user->id)}}" class="btn btn-dark">
		    			<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				  			<path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
						</svg>
					</a>
				</td>
				<form action="{{route('users.destroy', $user->id)}}" method="POST">
					{{ method_field('DELETE') }}
					@csrf 
			      	<td class="text-center">
			      		<button type="submit" class="btn btn-danger">&cross;</button>
			      	</td>
		      	</form>
		    </tr>
		@endforeach
	  </tbody>
	</table>
@endsection